### PR TITLE
Test running ui-service javascript tests

### PR DESCRIPTION
**Pull request by agrare**
https://github.com/ManageIQ/manageiq-ui-service/pull/1694

### CODE REVIEW

**Comment by Fryguy** [comment]
@agrare How do the tests themselve run?  Is it just `bundle exec rake`?  If so, should we just add a simple rake task?

**Comment by agrare** [comment]
@Fryguy https://github.com/ManageIQ/manageiq-ui-service/blob/master/.travis.yml#L20

**Comment by agrare** [comment]
Yeah we should be able to add a Rakefile that runs those two and replace those in the .travis.yml

**Comment by agrare** [comment]
Done, nice now we don't even need a different SCRIPT_CMD

**Pull request closed without merging**
