### PR TITLE
Cross repo tests for core PR #19212 (update to auth hooks)

### PR DESCRIPTION
**Pull request by djberg96**
I refactored the `auth_changed` callbacks in the `Authentication` model, so I want to make sure this didn't negatively impact any of the major repos. I've added four providers just to get a good sampling, and openshift and ovirt would be the most likely to be affected I think.

### CODE REVIEW

**Comment by djberg96** [comment]
IMO the Ovirt failure is not serious. The MiqQueue count is lower because fewer queues will be triggered. Prior to this PR, the update would always happen, even on create.

**Comment by agrare** [comment]
@djberg96 if this will cause the ovirt specs to fail we need a PR to ovirt to update the queue count

**Comment by djberg96** [comment]
@agrare roger, roger, will get that done today

**Comment by kbrock** [comment]
@djberg96 is this all set?

**Comment by djberg96** [comment]
@kbrock I punted on the original issue, so closing for now.

**Comment by kbrock** [comment]
ooh. I thought it was already merged. darn

**Pull request closed without merging**
