### PR TITLE
test miq 19684

### PR DESCRIPTION
**Pull request by kbrock**
test https://github.com/ManageIQ/manageiq/pull/19684

sorry, I botched up https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/46

trying again

### CODE REVIEW

**Comment by kbrock** [comment]
It would have been nice to use all these PRs in the core, and then run all the repos off of that.
But My cross-repo fu is not quite there yet.

**Comment by agrare** [comment]
@kbrock if you want to test core with all of those provider PRs you can add them all to the REPOS list

**Comment by cben** [comment]
Seems multiple values in REPOS didn't work, sent a fix.  See #49 and #50 runs using it.

**Comment by agrare** [comment]
Hey @cben !  The format for passing multiple repos is a comma separated list (see https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/44/files#diff-354f30a63fb0907d4ad57269548329e3R17).  I checked the README and you're right there are no examples of this.  I do like space separated though because it is what optimist is expecting for a multi-param anyway.

**Comment by kbrock** [comment]
thanks for help @cben and @agrare

**Comment by kbrock** [comment]
kicking

**Pull request closed without merging**
