### PR TITLE
testing active record virtual attributes (rails 5.2 support)

### PR DESCRIPTION
**Pull request by kbrock**
https://github.com/ManageIQ/activerecord-virtual_attributes/pull/62

### CODE REVIEW

**Comment by kbrock** [comment]
hmm. not sure how to run this against miq core repo. I did that wrong it seems

**Comment by kbrock** [comment]
all passed but manageiq (core) - but I can't see a failure in there. I'll kick again.

As LJ pointed out, this is running against rails 5.1

**Comment by Fryguy** [comment]
```
error manageiq-ui-classic@1.0.0: The engine "node" is incompatible with this module. Expected version ">= 10.13.0". Got "8.12.0"

error Found incompatible module
```

https://travis-ci.org/github/ManageIQ/manageiq-cross_repo-tests/jobs/667498995#L14206-L14207

**Comment by himdel** [comment]
should go green after https://github.com/ManageIQ/manageiq/pull/20018

**Comment by kbrock** [comment]
kicking

**Pull request closed without merging**
