### PR TITLE
add provider list to readme

### PR DESCRIPTION
**Pull request by d-m-u**
add the list of providers here as a reference

### CODE REVIEW

**Comment by chessbyte** [comment]
If you are going to do that, then please alphabetize them

**Comment by chessbyte** [comment]
@d-m-u why did you close this PR?  just curious

**Comment by d-m-u** [comment]
It really didn't sound from your previous comment like you were going to be willing to merge it.

**Comment by chessbyte** [comment]
I had no strong opinion one way or the other.  All I requested was to alphabetize the providers list, if we are to have one.  My only concern is that this list will change over time - so wondering if it makes more sense to figure out a way to generate the list dynamically from the project's [Gemfile](https://github.com/ManageIQ/manageiq/blob/master/Gemfile)

@Fryguy @agrare what are your thoughts?

**Comment by d-m-u** [comment]
> All I requested was to alphabetize the providers list, if we are to have one

And I followed that feedback over a month ago.

**Comment by agrare** [comment]
Agree that this list will get stale pretty quickly (already missing manageiq-providers-autosde).  @d-m-u I assume the purpose of this list is so that you can copy&paste into `.travis.yml` in order to "test with all providers"?

I think a command like https://github.com/ManageIQ/manageiq-cross_repo/issues/59 describes which could dynamically output the current list of providers would be the way to go, and could be used by https://github.com/ManageIQ/miq_bot/pull/454 going forward

**Comment by Fryguy** [comment]
We've had those issues opened for a long time though...I kind of like the list somewhere for convenience.  Maybe it could even just be a comment right in the .travis.yml?

With respect to this PR not being merged, it just slipped through the cracks because none of us monitor this repo for "real" pull requests.  That is, nearly all of the PRs are people running cross_repo-tests, as opposed to changing the framework for the cross_repo-tests.

**Pull request merged**
