### PR TITLE
Remove commented list of repos in .travis.yml

### PR DESCRIPTION
**Pull request by agrare**
Now that we have the ability to have miq-bot run on repo sets the need for this list is less important and makes the bot run's diff look more complicated: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/208/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485L20-R25

### CODE REVIEW

**Comment by NickLaMuro** [comment]
Stop causing me more merge conflicts dangit!!1!

Screen Shot 2020-11-30 at 1 49 29 PM

_shakes fist angerly_

**Comment by Fryguy** [comment]
@NickLaMuro I never would have expected a merge conflict from this repo.

**Comment by NickLaMuro** [comment]
@Fryguy this is actually the second time since the referenced PR has been open for so long.  The first as the addition of the comment in first place, and again when it was added again.

When you add/remove comments like this, any diff that was there in the previous form will have merge conflicts when the base file in `master` is changed.  Just like any other file in source control.

**Comment by chessbyte** [comment]
@NickLaMuro but you should not necessarily care about merge conflicts in this repo as this PR is not planned to be merged.

**Comment by NickLaMuro** [comment]
@chessbyte Tests will not run if there are merge conflicts, so yes... I care.

**Comment by NickLaMuro** [comment]
Also, to be perfectly clear, I am only mildly frustrated with this, and really there shouldn't be any action items out of this at all.  Just minor snark, which is why I didn't ping anybody with my original message as well.

**Pull request merged**
